---
title: ""
subtitle: ""
output:
  html_document:
    toc: false
    toc_float: true
    toc_depth: 2
    theme: yeti
    css: styles.css  # Linking the CSS file
    includes:
      in_header: scripts.js
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

<h5>My research interests relate to my curiosities at various stages of education. Mostly they pertain to statistics, machine learning and AI in the fields of actuarial science and finance. Alongside the published papers below (several Q1), I have visited numerous universities across Australia (Canberra, Sydney), Europe (Rotterdam, Amsterdam, Vienna, Slovakia, Stockholm, Linkoping) and Asia (China, Japan, South Korea) to discuss works with collaborators, friends, etc. - notably, helping contribute to papers and theses on simulating the return in boutique Swedish hedge funds that specialise in American life insurance policies, assisting research at UNSW looking at natural perils insurance and claims affordability, etc.  </h5> 

<br>

Huang, X., Ma, T., Liu, C. and Liu, S., 2023. GriT-DBSCAN: A spatial clustering algorithm for very large databases. Pattern Recognition, 142, p.109658.

[Paper](https://www.sciencedirect.com/science/article/abs/pii/S003132032300359X)

<br>

Spacial clustering is used in a wide array of applications in pattern recognition, including image analysis and person re-identification. Density-based scanning algorithms (DBSCAN) are used frequently as they identify clusters of arbitrary shapes well. However, DBSCAN has worst time complexity O(n^2). This paper introduces GriT-DBSCAN, which holds two key innovations: a grid tree for efficient neighboring grid queries and a FastMerging technique that prunes unnecessary distance calculations. These improvements reduce the time complexity to almost linear, making it scalable for large datasets. Additionally, two variants of the algorithm to handle different scenarios, such as low-density clusters and higher-dimensional data were created. 

<br>

Ma, L., Liu, C., Ma, T. and Liu, S., 2023. PaVa: a novel Path-based Valley-seeking clustering algorithm. Information Sciences, Volume 665, 120380. 

[Paper](https://www.sciencedirect.com/science/article/abs/pii/S0020025524002937)

<br>

Clustering is a fundamental technique in data analysis, used to group similar entities (e.g., customers, products, markets) for segmentation, targeting, and strategy formulation. Traditional clustering methods (e.g., k-means) struggle with arbitrarily shaped clusters and noisy data, which are common in real-world business scenarios (e.g., customer segmentation in retail, market analysis, or supply chain optimisation). This paper introduces PaVa, a novel clustering algorithm designed to handle arbitrarily shaped clusters and noisy data, which are common in real-world business scenarios. Unlike traditional methods like k-means or DBSCAN, PaVa uses minmax distance to transform irregular cluster boundaries into spherical shells, making it more effective for complex datasets. It also employs k-distance to adjust the Minimum Spanning Tree (MST), enhancing robustness to noise.

<br>

Cao, L., Sun, R., Ma, T. and Liu, C., 2023. On Asymmetric Correlations and Their Applications in Financial Markets. Journal of Risk and Financial Management, 16(3), p.187.

[Paper](https://www.mdpi.com/1911-8074/16/3/187)

<br>

Financial markets exhibit asymmetric correlations, where asset returns exhibit higher correlations during market downturns than upturns. This phenomenon has significant implications for portfolio management and risk assessment. This paper reviews various methods to test for asymmetric correlations, including extreme value theory, the H statistic, and model-free tests. It also looks at the root causes of these asymmetries, such as cash flow dynamics and firm-level return dispersions. For instance, during a recession, firms with similar sensitivities to macroeconomic shocks experience correlated declines in cash flows, leading to higher correlations in their stock returns. Additionally, firm-level return dispersions tend to decrease during downturns as most firms face simultaneous declines, further driving up correlations. Understanding these root causes is critical for portfolio management, as ignoring asymmetric correlations can lead to overestimating diversification benefits (impacting the effectiveness of say, hedging strategies using diversification) and underestimating downside risk. This research highlights the importance of incorporating asymmetric correlations into risk management and portfolio optimisation strategies.

<br>

Liu, Y., Wang, J., Yao, Z., Liu, C. and Liu, S., 2022. Diagnostic analytics for a GARCH model under skew-normal distributions. Communications in Statistics-Simulation and Computation, pp.1-25.

<br>

Liu, Y., Lin, Y., Song, X., Liu, C. and Liu, S., 2023. Nonnegative group bridge and application in financial index tracking. Statistical Papers, pp.1-21.

<br>

Liu, H., Ma, T., Liu, C. and Liu, S., 2023. Causal Responsibility Division of Chronological Continuous Treatment Based on Change-Point Detection. Entropy, 25(8), p.1164.

<br>

Liu, S., Wang, H., Liu, Y. and Liu, C., 2024. Matrix derivatives and Kronecker products for the core and generalized. Journal of Mathematical Analysis and Applications, p.128128.


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h6>
<center>*This site was last updated at `r format(Sys.time(), "%H:%M")` on `r format(Sys.Date(), "%d %b %Y")`*</center>
</h6>