---
title: ""
subtitle: ""
output:
  html_document:
    toc: false
    toc_float: true
    toc_depth: 2
    theme: yeti
    css: styles.css  # Linking the CSS file
    includes:
      in_header: scripts.js
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

<h5>我的研究兴趣源于我在不同教育阶段的好奇心，主要集中在精算科学和金融领域的统计学、机器学习和人工智能。除了下面的几篇已发表论文（多篇为Q1期刊），我还访问了澳大利亚（堪培拉、悉尼）、欧洲（鹿特丹、阿姆斯特丹、维也纳、斯洛伐克、斯德哥尔摩、林雪平）和亚洲（中国、日本、韩国）的多所大学，与合作伙伴、朋友等讨论学术成果。特别是，我曾参与撰写模拟专门投资于美国人寿保险单的瑞典精品对冲基金的回报的论文和论文项目，协助新南威尔士大学的研究，研究自然灾害保险和理赔的可负担性等问题。</h5>

<br>

Huang, X., Ma, T., Liu, C. and Liu, S., 2023. GriT-DBSCAN: A spatial clustering algorithm for very large databases. Pattern Recognition, 142, p.109658.

<br>

Ma, L., Liu, C., Ma, T. and Liu, S., 2023. PaVa: a novel Path-based Valley-seeking clustering algorithm. Information Sciences, Volume 665, 120380. 

<br>

Liu, Y., Wang, J., Yao, Z., Liu, C. and Liu, S., 2022. Diagnostic analytics for a GARCH model under skew-normal distributions. Communications in Statistics-Simulation and Computation, pp.1-25.

<br>

Liu, Y., Lin, Y., Song, X., Liu, C. and Liu, S., 2023. Nonnegative group bridge and application in financial index tracking. Statistical Papers, pp.1-21.

<br>

Liu, H., Ma, T., Liu, C. and Liu, S., 2023. Causal Responsibility Division of Chronological Continuous Treatment Based on Change-Point Detection. Entropy, 25(8), p.1164.

<br>

Liu, S., Wang, H., Liu, Y. and Liu, C., 2024. Matrix derivatives and Kronecker products for the core and generalized. Journal of Mathematical Analysis and Applications, p.128128.

<br>

Cao, L., Sun, R., Ma, T. and Liu, C., 2023. On Asymmetric Correlations and Their Applications in Financial Markets. Journal of Risk and Financial Management, 16(3), p.187.


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h6>
<center>*本站点最后更新时间为 `r format(Sys.time(), "%H:%M")`，更新日期为 `r format(Sys.Date(), "%Y年%m月%d日")`*</center>

</h6>