---
title: ""
subtitle: ""
output:
  html_document:
    toc: false
    toc_float: true
    toc_depth: 2
    theme: yeti
    css: styles.css  # Linking the CSS file
    include:
      in_header: scripts.js
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div style="margin-top: 88px;">
  <h1>Noemie Fox - 以及来自 Aware Super 的更多信息</h1>
</div>

<br>

<hr style="border-top: 1px solid grey; margin-left: 20px; margin-right: 20px;" />

<br>

我目前正在一家知名的养老金基金（Australian super，即澳大利亚的养老金）公司实习——Aware Super。他们最新的董事之一帮助运营一个致力于消除年轻女性进入体育障碍的组织。因此，他们与 Noemie Fox 有联系。在撰写本文时，她刚刚赢得了 2024 年巴黎奥运会独木舟越野赛的金牌，这是一项结合了两种不同风格独木舟项目的新赛事，并且增加了 2-3 名竞争者。因此，这项比赛显得相当激烈？

<br>

任何职业运动员，尤其是那些从事更独立运动的运动员，其实与现实世界中的公司非常相似。运动员的备战、专注、竞争以及执行，目标都是赢得比赛。在这些步骤中，涉及大量的人，时机非常重要，一致性也同样重要。正因为有这么多相似之处，Aware Super 邀请了 Noemie Fox 来进行炉边对话，然后继续讨论 Aware Super 及其管理层在“赢得退休”方面的目标。

<br>

我想记录下我的一些想法，以及让我印象深刻的内容。

<br>

从更广泛的角度来看，理解什么构成“赢”是非常重要的。无论大小，“赢”都是一个信号，表明事情正在朝正确的方向发展。它证明了正在执行的底层流程在推动进展。这就需要理解“进展”是什么以及“进展”在推动什么。所以，特别是在像独木舟这样以谦逊著称的运动中（面对波浪的冲击、翻船等等），理解什么构成一个小的胜利，在整个大胜利的框架中，又该如何庆祝这些小胜利，这是非常重要的。

<br>

正如所说，Fox 成功的关键工具在于将注意力从结果导向转移到过程驱动。什么是成功？成功的驱动力是什么？当一个人获得小的胜利时，如何证明自己能取得这些胜利？这形成了一个高度迭代的过程。在理解较少的情况下，甚至不确定什么对自己来说是成功。那么在取得胜利时，如何证明其合理性？接着，如何正向强化这一点？最后，如何通过正确的流程来优化新的获胜方式？对这个问题的答案会随着你对自己过去的胜利证明得越来越多而变得更加明显。

<br>

另一个关键点是 Fox 如何为巴黎奥运会调整自己的节奏。她之前专注于三个项目，但在巴黎，她只训练了一项项目。值得注意的是，这个项目是全新的，结合了两种独立风格的独木舟项目，并且增加了2-3名竞争者。因此，这个比赛从个人优化问题转变为更像一场战略性的“大逃杀”——这与现实世界中的商业非常相似。或许，进入一个利基市场，最终市场会有竞争。在这样的情况下，个人完美的重要性降低了——更重要的是了解竞争对手，他们的倾向性，然后在混乱中制定策略找到出路。

<br>

Fox 还谈到了一些她成功的驱动力；激情/目标、纪律/奉献精神以及坚定不移的专注/动力。我认为我仍在努力实现这些。

<br>

在 Fox 谈论完这些要点后，来自 Aware Super 的一些高管出面讨论了 Aware Super 的增长情况。值得注意的是，董事提到了两个关键点：什么是增长，为什么增长重要。他没有过多谈论如何实现增长……大概因为这是一个激励性的活动。但 Aware Super 的增长目标是将2030年“自然动量”从管理的3750亿澳元增长到4000亿澳元，以应对澳大利亚市场上另外两个主要竞争对手是其 3-4 倍规模的事实。关于为什么要增长，他提到了三点。首先，基金的增长可以减少固定成本，从而降低成员的费用。其次，基金的增长使得可以在更广泛的资产领域进行更好的投资。第三，成为一个更大的基金能够在政府立法和吸引优秀人才方面获得更多的倡导能力。这一点尤其明显，因为澳大利亚的其他大型养老金基金开始在初创企业的行为中发挥越来越大的作用，这是作为风险投资基金的主要投资者的结果。

<br>

董事在这里提到的关键点是公司的品牌建设至关重要。正如我最近从一些创业朋友那里听到的，一个强大的品牌应该与几个单一的词语或理念相关联。一个强大的品牌会立即让人联想到某些东西。对于 Aware Super，他们的新品牌目标是让人们想到“退休时选择的养老金基金”。

<br>

从管理咨询的角度，我对成功因素也很感兴趣。董事提到了一些：增加 55 岁以上会员的净数量，并尝试进入 45 岁以上的市场（因为竞争对手“分心了”）。其次，将 2.5% 的流失率降低到更接近 Australian Super 的 1.8%。第三，提升会员信心。很遗憾，我没能记下其余的内容，但从一个 MECE 的角度来看，这就是会员、会员的范围以及会员的信心。

<br>

最后，董事回顾了炉边对话。他提出了一些关键点。首先，专注；你不可能在每件事上都赢，所以要找到最重要的领域取得胜利，从而推动有意义的结果。其次，准备工作需要数年时间。第三，心态。

<br>

<h1>“我必须赢。”</h1>

<br>

<h1>“我能赢。”</h1>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h6>
<center>*This site was last updated at `r format(Sys.time(), "%H:%M")` on `r format(Sys.Date(), "%d %b %Y")`*</center>
</h6>