---
title: ""
subtitle: ""
output:
  html_document:
    toc: false
    toc_float: true
    toc_depth: 2
    theme: yeti
    css: styles.css  # Linking the CSS file
    include:
      in_header: scripts.js
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<div style="margin-top: 88px;">
  <h1>关于风险投资的一些思考</h1>
</div>

<br>


<hr style="border-top: 1px solid grey; margin-left: 20px; margin-right: 20px;" />

<br>

我在OIF Ventures（位于悉尼Double Bay，管理资产规模为A$500M的基金）工作7个月期间，最难忘的经历之一是陪同OIF的创始合伙人Jerry Stesel前往Optiver悉尼总部。

<br>

事情是这样的：那是2022年，Jerry有一位天使投资人朋友，投资了几位来自澳大利亚国立大学（ANU）的科学家（研究人员、学者），并请Jerry帮助引荐一些人脉。因为这些科学家正在开发一种液态冷却剂，Jerry认为有必要与可能需要液态冷却剂的人聊聊——也就是Optiver亚太区的技术负责人。

<br>

离开办公室时，Jerry显得相当乐观，甚至有些兴奋。他叫了一辆出租车。那是我第一次正式实习，也是第一次坐公司报销的出租车。当天阳光明媚，我穿着OIF的T恤。Double Bay总是那么美丽，尤其是蓝花楹树开得正盛。

<br>

在车上，我和Jerry聊天，他向我解释了他的想法，也提到了他曾是一名天使投资人。他还做了十年的投行工作，他笑称“时间太长了”。尽管如此，Jerry气色很好，皮肤也保持得很好，所以看起来依然很精神。

<br>

到了Optiver办公室，我们静静地等待科学家的到来。这时我才知道他们原本是来自堪培拉的（ANU所在地）。我点头表示理解（因为我出生在堪培拉）。

<br>

Optiver的办公室门口有一个小小的等候区，像那种小房子入口处常见的狭小空间。说实话，科学家们到来后，5个人站在这个狭小的地方有点尴尬。

<br>

但走进主办公区后，视觉效果令人惊叹。Optiver拥有整栋楼，于是他们在每一层楼都挖了一个洞，贯通到顶层，旁边有一个水景，从上到下流淌。这种设计很荒诞，但也可以理解。当然，在水景旁边就是主交易台等区域。总体来说，办公环境非常安静。每个人都专注于他们那5-6个显示器，屏幕以各种奇怪的角度摆放着。

<br>

值得一提的是，水景关闭了，原因后续会提到。所以楼层的洞口实际上变成了一个巨大的天窗。

<br>

我们随后见到了当时的技术负责人，一个叫Rohan或Rowan的人。他有一头亮红的头发和非常锐利的眼神。可能因为那时我才18岁，还没有遇到过很多这样强烈气场的人。

<br>

<br>
<br>
<br>
<br>
<br>

Rowan的帮助很大，因为他帮创始人们避免了走入死胡同。

<br>

像澳交所（ASX）的数据中心这样的地方，往往是最保守、最规避风险的。因此，他们不太可能愿意安装液态冷却剂。即使他们愿意安装，也会有一个安装期。为了充分利用这种据称能提高300%空间使用效率的液态冷却剂，数据中心需要彻底重新配置——这很可能会导致澳交所内正在进行交易的多方出现停机。

<br>

事实上，这也是Optiver坚决反对任何液态冷却剂的原因之一——有一次水景漏水，渗入了现场的数据中心，所以他们关闭了水景。

<br>

因此，Rowan真正帮助初创公司找到了合适的客户。他从技术和实际销售的角度都能理解业务需求。这一点至关重要，作为Optiver的技术负责人，无疑需要大量的业务拓展技能。

<br>

他还强调产品必须真正解决某人的需求。创始人们讨论了可能专注于电动汽车（将液态冷却剂应用于电池而不是数据中心）的方向。他还提到此类客户普遍挑剔的特性——比如Optiver曾经因为一栋建筑物阻碍了信号传输，影响了交易执行速度，于是他们干脆买下了那栋建筑物，以排除这个障碍，来获得微小的优势。

<br>

Rowan的帮助还体现在他拥有从两方面洞察问题的能力。他曾是一名软件工程师，后来逐渐晋升为Optiver亚太区的技术负责人。这意味着他不仅理解公司和类似组织的技术需求，还理解销售思维，最终能够将产品/服务与需要它们的客户匹配起来。

<br>

但那是2022年的事情了。我认为，尤其是在最近的AI热潮之后，数据中心比以往任何时候都重要。在ChatGPT等的推动下，下一步的进展将需要一个跨越式的变化。这将来自架构的改进，也会来自更多的训练数据——特别是多模态模型。而更多的训练数据意味着需要更多的数据中心。澳大利亚在这方面有机会，拥有大量的土地、金属（铜、铁），还有可能提升效率的液态冷却剂……





<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h6>
<center>*This site was last updated at `r format(Sys.time(), "%H:%M")` on `r format(Sys.Date(), "%d %b %Y")`*</center>
</h6>